#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 12
bspc config top_padding 8
#bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#a15cef"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Propios
bspc rule -a Alacritty state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a tk state=floating

# Modificados
sed -i "s/corner-radius = 8/corner-radius = 15/" /home/pablo/.config/picom.conf
xsetroot -cursor_name left_ptr
feh --bg-fill $HOME/Pictures/samuraipc.jpg
~/.config/polybar/launch.sh
#conky &
bspc config focus_follows_pointer false
picom &
udiskie -t &
nm-applet &
volumeicon &
